### ISSUE TITLE
Including project_options in the installed package for interface libraries

### ISSUE THREAD

**Issue by ClausKlein** [cpp-best-practices/project_options#108]
see https://github.com/cpp-best-practices/project_options/pull/105/commits/a178b9ce0a1bf06b37638cb0687c8d25fe650bc9

```bash
bash-3.2$ cd -
/Users/clausklein/cmake/cmakelib/test_install/build
bash-3.2$ ninja
[0/1] Re-running CMake...
-- vcpkg is already installed at /Users/clausklein/vcpkg.
-- Running vcpkg install
Detecting compiler hash for triplet x64-osx...
All requested packages are currently installed.
Restored 0 packages from /Users/clausklein/.cache/vcpkg/archives in 2.44 us. Use --debug to see more details.

Total elapsed time: 1.746 s

The package eigen3 provides CMake targets:

    find_package(Eigen3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)

The package fmt provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt)

    # Or use the header-only version
    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt-header-only)

-- Running vcpkg install - done
CMake Error at /Users/clausklein/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package):
  Found package configuration file:

    /Users/clausklein/cmake/cmakelib/install/share/myproj_header_only_lib/myproj_header_only_libConfig.cmake

  but it set myproj_header_only_lib_FOUND to FALSE so package
  "myproj_header_only_lib" is considered to be NOT FOUND.  Reason given by
  package:

  The following imported targets are referenced, but are missing:
  myproj::project_options myproj::project_warnings

Call Stack (most recent call first):
  CMakeLists.txt:45 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/clausklein/cmake/cmakelib/test_install/build/CMakeFiles/CMakeOutput.log".
See also "/Users/clausklein/cmake/cmakelib/test_install/build/CMakeFiles/CMakeError.log".
FAILED: CMakeFiles/impl-Debug.ninja build-Debug.ninja CMakeFiles/impl-Release.ninja build-Release.ninja CMakeFiles/impl-RelWithDebInfo.ninja build-RelWithDebInfo.ninja build.ninja 
/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S/Users/clausklein/cmake/cmakelib/test_install -B/Users/clausklein/cmake/cmakelib/test_install/build
ninja: error: rebuilding 'build.ninja': subcommand failed
bash-3.2$ 
```

**Comment by aminya** [comment]
This is impossible in CMake. The interface libraries cannot have private dependencies.

**Comment by ClausKlein** [comment]
> This is impossible in CMake. The interface libraries cannot have private dependencies.

I know, but if you install this interface, it is also **impossible** to use this header only lib without `project_options`!

**Comment by aminya** [comment]
We should also install project_options for header-only libraries.

**Comment by aminya** [comment]
Well, I don't think we actually need this. `package_project` already generates the `project_options` and `project_warnings` targets:

Running `test_install`, then looking at `myprojTargets.cmake`:

![image](https://user-images.githubusercontent.com/16418197/159191364-a552cebe-d589-4dee-b10a-5f88025be391.png)

**Comment by ClausKlein** [comment]
If I use a header only lib i.e. **boost::asio** I will not import there development setting like:

`--coverage`

`-Wpedantic -Werror`... or

the worst case:  **g++** specific warnings, if I want to use **clang++**

I created this issue to show it  is **a wrong usage** of `project_options` to export the `project_options` for every installed lib, independent of it is an `interface` or a normal lib!

**Comment by aminya** [comment]
The config files generated by CMake are not portable! They have absolute paths in them and are generated based on the options you pass to `project_options`.

To avoid having test/sanitizer-related flags in the generated config, you should use `FEATURE_TESTS` flag.

https://github.com/cpp-best-practices/cpp_vcpkg_project/blob/830685f328fba4bbdcfb0540d0fbcecd95aaab5c/CMakeLists.txt#L30

**Comment by aminya** [comment]
The example in the readme is updated. Now, the `FEATURE_TESTS` option handles the sanitizer flag exports.
