### ISSUE TITLE
CMAKE option warnings and errors not consistent (or documented)

### ISSUE THREAD

**Issue by LtdSauce** [cpp-best-practices/project_options#44]
I noticed that not all cmake warnings are turned into errors when the variable `WARNING_MESSAGE` is set to `SEND_ERROR`, hence `WARNINGS_AS_ERRORS` enabled.

For example a missing `clang-tidy` will produce an error if the corresponding option is set (see [StaticAnalyzer.cmake:32](https://github.com/cpp-best-practices/project_options/blob/main/src/StaticAnalyzers.cmake)).
On the other hand a missing Sanitizer is always producing a warning (see  [Sanitizers.cmake:27](https://github.com/cpp-best-practices/project_options/blob/main/src/Sanitizers.cmake)). 
Same goes for a missing `ccache` executable (see [cache.cmake:29](https://github.com/cpp-best-practices/project_options/blob/main/src/Cache.cmake)).

I cannot find any explantation why those are treated different, which kind of confuses me.

Would it be possible to add comments why some do not use the `WARNING_MESSAGE` variable, if that had been done on purpose?
Which seems the case at least for clang-tidy if i correctly understand #30.

**Comment by LtdSauce** [comment]
Maybe something like `ENABLE_IF_<tool>` or `OPTIONAL_ENABLE_<tool>` could be used for those to make it explicit, that it is always a warning and never an error?

**Comment by aminya** [comment]
`WARNINGS_AS_ERRORS` is used for the tools that analyze the code semantically. The compiler itself, clang-tidy, cppcheck and any other static analyzer.

**Comment by LtdSauce** [comment]
Ah i see! That makes sense.

Would you consider this to be common knowledge (that i didn't have) or is it worth adding a comment to the `WARNINGS_AS_ERRORS` option?

**Comment by aminya** [comment]
Yes, we should add this to the docs. 

P.S: I don't personally use WARNINGS_AS_ERRORS because I don't need an external force for addressing the warnings. 😁

**Comment by aminya** [comment]
@LtdSauce are you interested in improving the docs here?

**Comment by LtdSauce** [comment]
If i find the time i could open a PR.

I would suggest something like:

"Turns compiler and static code analyzer warnings into errors. This also effects cmake warnings related to those."

**Comment by aminya** [comment]
Thanks! I added the commit
