### ISSUE TITLE
How to pass flags to CLANG_WARNINGS?

### ISSUE THREAD

**Issue by ljishen** [cpp-best-practices/project_options#59]
It looks like that CLANG_WARNINGS only accepts a single parameter. So the question is how can I pass multiple flags to CLANG_WARNINGS?

**Comment by aminya** [comment]
Thanks for catching the bug. It is fixed in v0.15.1. Please upgrade.

**Comment by ljishen** [comment]
Thanks for your quick action! I'm actually looking for a way to append compiler flags (instead of overriding). I'm currently using `add_compile_options()`, but it's better to have a parameter in `dynamic_project_options()` for appending flags.

**Comment by aminya** [comment]
You're welcome! 

Adding more warnings is easy:
```cmake
target_compile_options(project_warnings INTERFACE -Wsomething)
```

BTW, what warning do you want to add? We tried to include all of it.

**Comment by ljishen** [comment]
Cool! I didn't know `target_compile_options()` can append flags. The flags I added may not be applicable for general projects, and some of them may even be dangerous. They are here https://github.com/DPDK/dpdk/blob/main/config/meson.build#L253-L272 for just in case you find something useful.

**Comment by aminya** [comment]
Yeah, it can add those. We should probably add the example in the readme. 

Thank you for the list. 

I opened two issues to address these:
#62 
#61

**Comment by ljishen** [comment]
Thanks for the update. It's exciting to see this project being more useful and powerful.
