### ISSUE TITLE
Enable StaticAnalyzers for C

### ISSUE THREAD

**Issue by ljishen** [cpp-best-practices/project_options#64]
Currently only CXX are supported by cppcheck, clang-tidy, and include-what-you-use. It would be great to have them enabled for C as well.

- [x] Set C standard: #65 
- [ ] Clang-tidy for C #78
- [ ] Cppecheck for C #77

**Comment by aminya** [comment]
Also, #78 for clang-tidy

```
https://github.com/cpp-best-practices/project_options/archive/refs/heads/c-clangtidy.zip
```

**Comment by ljishen** [comment]
@aminya Yes, I'll let you know.

**Comment by ljishen** [comment]
@aminya I've posted the feedback on the page of the corresponding pull request.
