### ISSUE TITLE
Warning is valid for C++/ObjC++ but not for C

### ISSUE THREAD

**Issue by ljishen** [cpp-best-practices/project_options#69]
When compiling with GCC, it complains some warnings are not for C. We may need to set different warnings for different languages.

```
cc1: warning: command-line option ‘-Wnon-virtual-dtor’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wold-style-cast’ is valid for C++/ObjC++ but not for C                                                                                            
cc1: warning: command-line option ‘-Woverloaded-virtual’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-Wuseless-cast’ is valid for C++/ObjC++ but not for C
```

**Comment by aminya** [comment]
What version of gcc is that?

**Comment by ljishen** [comment]
It's "gcc-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0".

**Comment by aminya** [comment]
I wish there was a flag that could pass to silence these warnings. Otherwise, we have to exclude these manually for C.

**Comment by aminya** [comment]
Does `-permissive` work for non MSVC compilers?

**Comment by aminya** [comment]
#76 should fix this

**Comment by ClausKlein** [comment]
> Does `-permissive` work for non MSVC compilers?

I thing yes, but it has the inverse meaning, you should not use it!
