### ISSUE TITLE
CMake's `FetchContent` fails in the "untar" step on Windows

### ISSUE THREAD

**Issue by Nosenzor** [cpp-best-practices/project_options#94]
It seems to be a a problem on Windows Cmake (i have no problem on Mac or Linux) but any way I open an issue if you know a turn-around.... 
-- extracting... [tar xfz]
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: K:/Project/_deps/_project_options-subbuild/_project_options-populate-prefix/src/v0.18.1.zip
-- extracting... [error clean up]
CMake Error at _project_options-subbuild/_project_options-populate-prefix/src/_project_options-populate-stamp/extract-_project_options-populate.cmake:33 (message):
  error: extract of
  'K:/Project/_deps/_deps/_project_options-subbuild/_project_options-populate-prefix/src/v0.18.1.zip'
  failed

**Comment by aminya** [comment]
What version of Windows is it?

**Comment by ClausKlein** [comment]
> It seems to be a a problem on Windows Cmake (i have no problem on Mac or Linux) but any way I open an issue if you know a turn-around....

This may be an alternative way, using git, and download to a central directory  `~/cache/CMP/... `
```cmake
# ---- Add dependencies via CPM ----
# see https://github.com/cpm-cmake/CPM.cmake for more info
include(cmake/CPM.cmake)

# Add project_options v0.18.0, but my version! CK
# https://github.com/cpp-best-practices/project_options
CPMAddPackage("gh:ClausKlein/cmakelib#865af7a1339c03cc8b3cab0d3dcd01ec789f456c")
list(APPEND CMAKE_MODULE_PATH ${ProjectOptions_SRC_DIR})
```

**Comment by Nosenzor** [comment]
That's sound very handy. Let me try.

**Comment by aminya** [comment]
> That's sound very handy. Let me try.

This link doesn't use the official project_options (this repository)

**Comment by aminya** [comment]
Since you didn't give more information about the Windows version and I cannot reproduce it, I have to close this issue for now. 

> > That's sound very handy. Let me try.
> 
> This link doesn't use the official project_options (this repository)
